version: "3.8"

services:
  web:
    build: .
    image: cocodrilo-fitness:prod
    ports:
      - "3000"
    networks:
      - agent-net
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.docker.network=agent-net"
        - "traefik.enable=true"
        - "traefik.http.routers.cocodrilo-fitness.rule=Host(`cocodrilo-fitness.paragu-ai.com`)"
        - "traefik.http.routers.cocodrilo-fitness.entrypoints=websecure"
        - "traefik.http.routers.cocodrilo-fitness.tls=true"
        - "traefik.http.routers.cocodrilo-fitness.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.cocodrilo-fitness.loadbalancer.server.port=3000"

networks:
  agent-net:
    external: true
